-- MySQL Script generated by MySQL Workbench
-- Sun Dec  6 12:26:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalho_modulo_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho_modulo_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho_modulo_2` DEFAULT CHARACTER SET utf8 ;
USE `trabalho_modulo_2` ;

-- -----------------------------------------------------
-- Table `trabalho_modulo_2`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_modulo_2`.`estado` (
  `CodEstadoIBGE` INT NOT NULL,
  `NomeEstado` VARCHAR(45) NOT NULL,
  `SiglaEstado` VARCHAR(2) NOT NULL,
  `Regiao` VARCHAR(45) NULL,
  PRIMARY KEY (`CodEstadoIBGE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_modulo_2`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_modulo_2`.`cidade` (
  `CodigoCompletoIBGE` VARCHAR(45) NOT NULL,
  `CodigoCidadeIBGE` VARCHAR(10) NOT NULL,
  `NomeCidade` VARCHAR(150) NOT NULL,
  `CodEstadoIBGE` INT NOT NULL,
  PRIMARY KEY (`CodigoCompletoIBGE`),
  INDEX `fk_cidade_estado_idx` (`CodEstadoIBGE` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`CodEstadoIBGE`)
    REFERENCES `trabalho_modulo_2`.`estado` (`CodEstadoIBGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_modulo_2`.`tipounidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_modulo_2`.`tipounidade` (
  `idTipoUnidade` INT NOT NULL AUTO_INCREMENT,
  `dscTipoUnidade` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idTipoUnidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_modulo_2`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_modulo_2`.`imovel` (
  `idImovel` INT NOT NULL AUTO_INCREMENT,
  `codRegistro` VARCHAR(45) NOT NULL,
  `Disponibilidade` CHAR(1) NULL,
  `areaImovel` DECIMAL(6,2) NULL,
  `valorIPTU` DECIMAL(10,2) NULL,
  `valorCondominio` DECIMAL(10,2) NULL,
  `qtdeQuartos` INT NULL,
  `qtdeBanheiro` INT NULL,
  `qtdeSuite` INT NULL,
  `qtdeSala` INT NOT NULL,
  `qtdeVagas` INT NOT NULL,
  `CodigoCompletoIBGE` VARCHAR(45) NOT NULL,
  `idTipoUnidade` INT NOT NULL,
  PRIMARY KEY (`idImovel`),
  INDEX `fk_imovel_cidade1_idx` (`CodigoCompletoIBGE` ASC) VISIBLE,
  INDEX `fk_imovel_tipounidade1_idx` (`idTipoUnidade` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_cidade1`
    FOREIGN KEY (`CodigoCompletoIBGE`)
    REFERENCES `trabalho_modulo_2`.`cidade` (`CodigoCompletoIBGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_tipounidade1`
    FOREIGN KEY (`idTipoUnidade`)
    REFERENCES `trabalho_modulo_2`.`tipounidade` (`idTipoUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_modulo_2`.`caracteristicasGerais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_modulo_2`.`caracteristicasGerais` (
  `idcaracteristicasGerais` INT NOT NULL AUTO_INCREMENT,
  `dsccaracteristicasGerais` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idcaracteristicasGerais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_modulo_2`.`caracteristicageralImovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_modulo_2`.`caracteristicageralImovel` (
  `idCaracteristicasImovel` INT NOT NULL AUTO_INCREMENT,
  `temCaracteristica` TINYINT(1) NULL,
  `idImovel` INT NOT NULL,
  `idcaracteristicasGerais` INT NOT NULL,
  PRIMARY KEY (`idCaracteristicasImovel`),
  INDEX `fk_caracteristicageralImovel_imovel1_idx` (`idImovel` ASC) VISIBLE,
  INDEX `fk_caracteristicageralImovel_caracteristicasGerais1_idx` (`idcaracteristicasGerais` ASC) VISIBLE,
  CONSTRAINT `fk_caracteristicageralImovel_imovel1`
    FOREIGN KEY (`idImovel`)
    REFERENCES `trabalho_modulo_2`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caracteristicageralImovel_caracteristicasGerais1`
    FOREIGN KEY (`idcaracteristicasGerais`)
    REFERENCES `trabalho_modulo_2`.`caracteristicasGerais` (`idcaracteristicasGerais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
